Yihui/Controllers/InternalAssignmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Yihui.Models;
using Yihui.DAL;
using WebMatrix.WebData;
using System.IO;

namespace Yihui.Controllers
{
    [Authorize]
    public class InternalAssignmentController : Controller
    {
        private YihuiEntities db = new YihuiEntities();

        //
        // GET: /InternalAssignment/
        [Authorize(Roles = "Internal")]
        public ActionResult Index()
        {
            var userId = WebSecurity.GetUserId(User.Identity.Name);
            var assignments = db.Assignments.OrderByDescending(a => a.ModifiedDate).Where(a=>a.Deleted!=true && a.UserId==userId);
            return View(assignments.ToList());
        }

        //
        // GET: /InternalAssignment/Details/5
        [Authorize(Roles = "Internal")]
        public ActionResult Details(int id = 0)
        {
            Assignment assignment = null;

            if (id == 0)
            {
                assignment = db.Assignments.OrderByDescending(a => a.ModifiedDate).FirstOrDefault();
            }
            else
            {
                assignment = db.Assignments.Find(id);
            }

            if (assignment == null)
            {
                return HttpNotFound();
            }

            IEnumerable<Status_Master> states = null;

            if (assignment.StatusId == (int)Common.Status.Not_Started)
            {
                states = db.Status_Master;
            }
            else if (assignment.StatusId == (int)Common.Status.Completed)
            {
                int finish = (int)Common.Status.Completed;
                states = db.Status_Master.Where(s => s.StatusId == finish);
            }
            else 
            {
                int notStart = (int)Common.Status.Not_Started;
                states = db.Status_Master.Where(s => s.StatusId != notStart);
            }

            ViewBag.StatusId = new SelectList(states, "StatusId", "Status", assignment.StatusId);
            ViewBag.items = db.AssignmentItems.Where(a => a.AssignmentId == id && a.Deleted == false).ToList();
            return PartialView(assignment);
        }

        public FileResult DisplayPDF(int id)
        {
            Assignment assignment = db.Assignments.Find(id);
            if (assignment == null)
            {
                return null;
            }

            if (!string.IsNullOrEmpty(assignment.POPath))
            {
                return File(assignment.POPath, "application/pdf");
            }

            return null;
        }

        //
        // GET: /InternalAssignment/ViewMap
        [Authorize(Roles = "Internal")]
        public ActionResult ViewMap(int id = 0)
        {
            Assignment assignment = db.Assignments.Find(id);
            if (assignment == null)
            {
                return HttpNotFound();
            }

            ViewBag.DesAddress = assignment.Address;

            return View();
        }

        //
        // GET: /InternalAssignment/Create
        [Authorize(Roles = "Internal")]
        public ActionResult Create()
        {
            string userRole = Common.UserRoles.Internal.ToString();

            var users = (from userRoles in db.UsersInRoles
                         join role in db.Roles on userRoles.RoleId equals role.RoleId
                         join user in db.Users on userRoles.UserId equals user.UserId
                         where role.RoleName == userRole && user.Deleted != true
                         select user).ToList();

            ViewBag.PriorityId = new SelectList(db.Priority_Master, "PriorityId", "Priority");
            ViewBag.StatusId = new SelectList(db.Status_Master, "StatusId", "Status");
            ViewBag.UserId = new SelectList(users, "UserId", "UserName");
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "CompName");
            ViewBag.ItemId = new SelectList(db.Items.Where(a => a.Deleted == false), "ItemId", "Name");
            return PartialView();
        }

        //
        // POST: /InternalAssignment/Create
        [Authorize(Roles = "Internal")]
        [HttpPost]
        public ActionResult Create(Assignment assignment, HttpPostedFileBase file)
        {
            var items = Request["ItemId"];
            var wheights = Request["Weight"];
            List<string> itemList = null;
            List<string> wheightList = null;

            if (!string.IsNullOrEmpty(items) && !string.IsNullOrEmpty(wheights))
            {
                itemList = items.Split(',').ToList();
                wheightList = wheights.Split(',').ToList();

                if (itemList.Count < 0 || wheightList.Count < 0)
                {
                    ModelState.AddModelError("Items", "Please select a item");
                }
            }
            else
            {
                ModelState.AddModelError("Items", "Please select a item");
            }

            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string pic = System.IO.Path.GetFileName(file.FileName);
                    string path = Server.MapPath("~/PO/");
                    string fullPath = System.IO.Path.Combine(path, pic);

                    if (!Directory.Exists(path))
                    {
                        DirectoryInfo di = Directory.CreateDirectory(path);
                    }

                    // file is uploaded
                    file.SaveAs(fullPath);
                    assignment.POPath = fullPath;
                }

                var userId = WebSecurity.GetUserId(User.Identity.Name);
                assignment.UserId = userId;
                assignment.Deleted = false;
                assignment.CreatedDate = DateTime.Now;
                assignment.CreatedBy = userId;
                assignment.ModifiedBy = userId;
                assignment.ModifiedDate = DateTime.Now;
                db.Assignments.Add(assignment);
                db.SaveChanges();

                for (int x = 0; x < itemList.Count; x++)
                {
                    if (!string.IsNullOrEmpty(wheightList[x]))
                    {
                        AssignmentItem assignmentItem = new AssignmentItem { AssignmentId = assignment.AssignmentId, ItemId = Convert.ToInt32(itemList[x]), Weight = Convert.ToDouble(wheightList[x]) };
                        assignmentItem.CreatedBy = userId;
                        assignmentItem.CreatedDate = DateTime.Now;
                        assignmentItem.Deleted = false;
                        db.AssignmentItems.Add(assignmentItem);
                        db.SaveChanges();
                    }
                }

                return RedirectToAction("Index");
            }

            string userRole = Common.UserRoles.Internal.ToString();

            var users = (from userRoles in db.UsersInRoles
                         join role in db.Roles on userRoles.RoleId equals role.RoleId
                         join user in db.Users on userRoles.UserId equals user.UserId
                         where role.RoleName == userRole && user.Deleted != true
                         select user).ToList();

            ViewBag.PriorityId = new SelectList(db.Priority_Master, "PriorityId", "Priority", assignment.PriorityId);
            ViewBag.StatusId = new SelectList(db.Status_Master, "StatusId", "Status", assignment.StatusId);
            ViewBag.UserId = new SelectList(users, "UserId", "UserName", assignment.UserId);
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "CompName");
            ViewBag.ItemId = new SelectList(db.Items.Where(a => a.Deleted == false), "ItemId", "Name");
            return View(assignment);
        }

        //
        // GET: /InternalAssignment/Edit/5
        [Authorize(Roles = "Internal")]
        public ActionResult Edit(int id = 0)
        {
            Assignment assignment = db.Assignments.Find(id);
            if (assignment == null)
            {
                return HttpNotFound();
            }

            string userRole = Common.UserRoles.Internal.ToString();

            var users = (from userRoles in db.UsersInRoles
                         join role in db.Roles on userRoles.RoleId equals role.RoleId
                         join user in db.Users on userRoles.UserId equals user.UserId
                         where role.RoleName == userRole && user.Deleted != true
                         select user).ToList();

            ViewBag.PriorityId = new SelectList(db.Priority_Master, "PriorityId", "Priority", assignment.PriorityId);
            ViewBag.StatusId = new SelectList(db.Status_Master, "StatusId", "Status", assignment.StatusId);
            ViewBag.UserId = new SelectList(users, "UserId", "UserName", assignment.UserId);
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "CompName", assignment.CustomerId);

            ViewBag.Items = db.Items.Where(a => a.Deleted == false).ToList();
            ViewBag.MyItems = db.AssignmentItems.Where(a => a.AssignmentId == assignment.AssignmentId && a.Deleted == false).ToList();

            return View(assignment);
        }

        //
        // POST: /InternalAssignment/Edit/5

        [HttpPost]
        [Authorize(Roles = "Internal")]
        public ActionResult Edit(Assignment assignment, HttpPostedFileBase file)
        {
            var items = Request["ItemId"];
            var wheights = Request["Weight"];
            List<string> itemList = null;
            List<string> wheightList = null;

            if (!string.IsNullOrEmpty(items) && !string.IsNullOrEmpty(wheights))
            {
                itemList = items.Split(',').ToList();
                wheightList = wheights.Split(',').ToList();

                if (itemList.Count < 0 || wheightList.Count < 0)
                {

Yihui/Views/InternalAssignment/Create.cshtml
@model Yihui.Models.Assignment

@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/jqueryval")

<style>

    .btn-file {
    position: relative;
    overflow: hidden;
}
.btn-file input[type=file] {
    position: absolute;
    top: 0;
    right: 0;
    min-width: 100%;
    min-height: 100%;
    font-size: 100px;
    text-align: right;
    filter: alpha(opacity=0);
    opacity: 0;
    outline: none;
    background: white;
    cursor: inherit;
    display: block;
}
input[readonly] {
  background-color: white !important;
  cursor: text !important;
}
</style>
<div class="modal-content">
    <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><img src="~/Images/user/button_cancel.png" width="20" height="20"/></button>
                <h4 class="modal-title">ADD NEW ASSIGNMENT</h4>
                 <p class="modal-title pull-right">Created on @DateTime.Now.ToShortDateString()</p>
            </div>
    <div class="modal-body">
       
            @using (Html.BeginForm("Create", "InternalAssignment", FormMethod.Post,
                            new { enctype = "multipart/form-data" }))
                {
                    @Html.ValidationSummary(true)

                    <fieldset>
                        
                        <div class="col-md-8">
                            <div class="form-group">
                                <div class="col-sm-4">
                                    <label class="control-label">@Html.LabelFor(model => model.CustomerId, "Customer")</label>
                                </div>
                                <div class="col-sm-8">
                                    @Html.DropDownList("CustomerId", (SelectList)ViewBag.CustomerId, new { @id = "CustomerId", @onchange = "javascript:GetCustomerDetails(this.value);", @class = "form-control" })
                                    <p class="alert-danger">@Html.ValidationMessageFor(model => model.CustomerId)</p>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-4">
                                    <label class="control-label">@Html.LabelFor(model => model.Name) </label>
                                </div>
                                <div class="col-sm-8">
                                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                                    <p class="alert-danger">@Html.ValidationMessageFor(model => model.Name)</p>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-4">
                                    <label class="control-label">@Html.LabelFor(model => model.Address) </label>
                                </div>
                                <div class="col-sm-8">
                                    @Html.TextBoxFor(model => model.Address, new { @class = "form-control" })
                                    <p class="alert-danger">@Html.ValidationMessageFor(model => model.Address)</p>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-4">
                                    <label class="control-label">@Html.LabelFor(model => model.Description) </label>
                                </div>
                                <div class="col-sm-8">
                                    @Html.TextBoxFor(model => model.Description, new { @class = "form-control input-lg" })
                                    <p class="alert-danger">@Html.ValidationMessageFor(model => model.Description)</p>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-4">
                                    <label class="control-label">@Html.LabelFor(model => model.PriorityId, "Priority") </label>
                                </div>
                                <div class="col-sm-8">
                                    @Html.DropDownList("PriorityId", (SelectList)ViewBag.PriorityId, new { @class = "form-control" })
                                    <p class="alert-danger">@Html.ValidationMessageFor(model => model.PriorityId)</p>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-4">
                                    <label class="control-label">@Html.LabelFor(model => model.StatusId, "Status") </label>
                                </div>
                                <div class="col-sm-8">
                                    @Html.DropDownList("StatusId", (SelectList)ViewBag.StatusId, new { @class = "form-control" })
                                    <p class="alert-danger">@Html.ValidationMessageFor(model => model.PriorityId)</p>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-4">
                                    <label class="control-label">@Html.LabelFor(model => model.StartDate) </label>
                                </div>
                                <div class="col-sm-8">
                                    @Html.TextBoxFor(model => model.StartDate, new { @class = "form-control" })
                                    <p class="alert-danger">@Html.ValidationMessageFor(model => model.StartDate)</p>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-4">
                                    <label class="control-label">@Html.LabelFor(model => model.EndDate) </label>
                                </div>
                                <div class="col-sm-8">
                                    @Html.TextBoxFor(model => model.EndDate, new { @class = "form-control" })
                                    <p class="alert-danger">@Html.ValidationMessageFor(model => model.EndDate)</p>
                                </div>
                            </div> 
                            
                            <div class="form-group">
                                <div class="col-sm-4">
                                    <label class="control-label">POPath</label>
                                </div>
                                <div class="col-sm-8">
                                    <div class="input-group col-sm-12">
                                        <span class="input-group-btn">
                                            <span class="btn btn-default btn-file">Browse&hellip;
                                    <input type="file" name="file" id="file" multiple>
                                            </span>
                                        </span>
                                        <input type="text" class="form-control" readonly>
                                    </div>
                                </div>
                            </div> 
                            
                            <div class="form-group">
                             <div class="col-sm-4">
                                <label class="control-label">Item</label>
                            </div>
                            <div class="col-sm-8">
                                <table id="div_Items" class="table">
                                    <tr class="">                                       
                                        <th>
                                            <input type="button" class="BtnPlus btn btn-info" value="ADD LINE" /></th>
                                        <th>
                                            <input type="button" class="BtnMinus btn btn-danger" value="REMOVE" /></th>
                                    </tr>
                                    <tr id="div_Item" class="info">
                                        <td>
                                            @Html.DropDownList("ItemId", (SelectList)ViewBag.ItemId)
                                        </td>
                                        <td>
                                            @Html.TextBox("Weight", "", new { @class = "form-control" })
                                        </td>
                                    </tr>
                                </table>
                                <p class="alert-danger">@Html.ValidationMessage("Items")</p>
                            
                            </div>
                        </div> 

                            <div class="form-group">
                            <div class="col-sm-offset-4 col-sm-10">
                                <button type="submit" class="btn btn-success">Save</button>
                                <a href="/InternalAssignment/Index" class="btn btn-default">Cancel</a>
                            </div>
                        </div>                         

                        </div>
                        <div class="col-md-4">
                            <h4 style="text-align:center">Address and Contact Number</h4>
                            <div class="col-md-6"><strong> Address :</strong> </div><div class="col-md-6"><p class="pull-right" id="Address"></p></div> <br />
                               <div class="col-md-6"> <strong>Contact No : </strong> </div><div class="col-md-6"><p class="pull-right" id="ContactNo"></p> </div>

                        </div>
                    </fieldset>
                }

                
            
    </div>
</div>


<script type="text/javascript">
    $(function () {
        $('#approve-btn').click(function () {
            $('#modal-container').modal('hide');
        });
    });
</script>



<script type="text/javascript">
    $(document).ready(function () {

        var rowCount = 1;

        function addRow() {
            $('#div_Items tr:last').after($('#div_Item').clone());
            rowCount++;
        };

        $("#div_Items").on("click", ".BtnPlus", addRow);

        function deleteRow() {
            if (rowCount > 1) {
                $('#div_Items tr:last').remove();
                rowCount--;
            }
        };
        $("#div_Items").on("click", ".BtnMinus", deleteRow);
    });

    function GetCustomerDetails(_cusId) {

        var url = "/InternalAssignment/GetCustomerDetails/";

        $.ajax({
            url: url,
            data: { cusId: _cusId },
            cache: false,
            type: "POST",
            success: function (data) {
                $("#Address").text(data.Address);
                $("#ContactNo").text(data.ContactNo);
            },
            error: function (reponse) {
                alert("error : " + reponse);
            }
        });

    }


    //$(document).on('change', '.btn-file :file', function () {
    //    var input = $(this),
    //        numFiles = input.get(0).files ? input.get(0).files.length : 1,
    //        label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
    //    input.trigger('fileselect', [numFiles, label]);
    //});

    //$(document).ready(function () {
    //    $('.btn-file :file').on('fileselect', function (event, numFiles, label) {

    //        var input = $(this).parents('.input-group').find(':text'),
    //            log = numFiles > 1 ? numFiles + ' files selected' : label;

    //        if (input.length) {
    //            input.val(log);
    //        } else {
    //            if (log) alert(log);
    //        }

    //    });
    //});

</script>

Yihui/Views/InternalAssignment/Delete.cshtml
@model Yihui.Models.Assignment

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_DataList.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Assignment</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Priority_Master.Priority)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Priority_Master.Priority)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Status_Master.Status)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Status_Master.Status)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.StartDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.StartDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.EndDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EndDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.User.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.User.UserName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CustomerId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Customer.CompName)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Yihui/Views/InternalAssignment/Index.cshtml
@model IEnumerable<Yihui.Models.Assignment>

@{
    ViewBag.Title = "My Jobs";
    Layout = "~/Views/Shared/_UserProfile.cshtml";
}

@Styles.Render("~/Content/css")

<style>
    .fade {
        display: block;
        position: fixed;
        top: 0%;
        left: 0%;
        width: 100%;
        height: 100%;
        background-color: #000;
        z-index: 1001;
        -moz-opacity: 0.7;
        opacity: .70;
        filter: alpha(opacity=70);
    }

    .popup {
        display: block;
        position: absolute;
        top: 50%;
        left: 50%;
        width: 300px;
        height: 200px;
        margin-left: -150px;
        margin-top: -100px;
        padding: 10px;
        border: 2px solid #FFF;
        background: #CCC;
        z-index: 1002;
        overflow: visible;
    }

    .modal-content {
        width: 900px !important;
        margin: 30px auto !important;
    }
</style>
<div class="navbar navbar-default" role="navigation">

    <div class="navbar-inner">
        @* <button type="button" class="navbar-toggle pull-left animated flip">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>*@

        <a class="navbar-brand">
            <span>My Job</span></a>
        <div class="pull-left what">
            @if (Request.IsAuthenticated)
            { 
                <text>
                <div class="singinas">
                    Singed in as,<a href="/User/MyProfile"> @User.Identity.Name</a> &nbsp; &nbsp; &nbsp;
                </div>
                @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                {
                    @Html.AntiForgeryToken()
<a class="logoff" href="javascript:document.getElementById('logoutForm').submit()">Click here to Log Out</a>
                }
                </text>
            }
        </div>
        <div class="pull-right newass">
            <a class="modal-link btn btn-info" href="/InternalAssignment/Create">
                <i class="glyphicon glyphicon-plus"></i><span class="hidden-sm hidden-xs">Add New Assignment</span>
            </a>
        </div>
        @*@Html.ActionLink("Create ", "Create", "InternalAssignment", null, new { @class = "modal-link btn btn-success" })*@


    </div>
</div>


<div class="ch-container">
    <div class="row">

        <!-- left menu starts -->
        <div class="col-xs-10 col-md-3">

            <ul class="nav nav-pills nav-stacked main-menu" id="jobs">
                <li class="nav-header">Today, @DateTime.Now.ToShortDateString()</li>


                @foreach (var item in Model)
                {
                    <li class="job"  id="@(item.AssignmentId)">
                        <a class="ajax-link">
                            <span>
                                <span class="1 col-xs-8" style="float: left; color: black">
                                    @Html.DisplayFor(modelItem => item.Name)<br />
                                    @Html.DisplayFor(modelItem => item.Customer.CompName)
                                </span>
                                <span class="2" style="float: right">


                                    @if (Html.DisplayFor(modelItem => item.Status_Master.Status).ToString() == "In Progress")
                                    {
                                        <div class="inpro"></div>
                                    }
                                    else if (Html.DisplayFor(modelItem => item.Status_Master.Status).ToString() == "Not Started")
                                    {
                                        <div class="notstart"></div>
                                    }
                                    else if (Html.DisplayFor(modelItem => item.Status_Master.Status).ToString() == Yihui.Common.Status.Completed.ToString())
                                    { 
                                        <div class="finished"></div>
                                    }
                                    else if (Html.DisplayFor(modelItem => item.Status_Master.Status).ToString() == "On Hold")
                                    { 
                                        <div class="onhold"></div>
                                    }
                                    else
                                    {
                                        <div class="canceled"></div>
                                    }
                                    <div class="prio">@Html.DisplayFor(modelItem => item.Priority_Master.Priority)</div>

                                </span>
                            </span>

                        </a></li>
                }


            </ul>

        </div>
        <!--/span-->
        <!-- left menu ends -->

        <noscript>
            <div class="alert alert-block col-md-12">
                <h4 class="alert-heading">Warning!</h4>

                <p>
                    You need to have <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a>
                    enabled to use this site.
                </p>
            </div>
        </noscript>

        <div id="DetailView" class="col-xs-12 col-md-9">
            <!-- content starts -->



        </div>
        <!--/#content.col-md-0-->
    </div>
    <!--/fluid-row-->
</div>

<div id="CreateView" class="popup">
</div>

<div id="modal-container" class="modal" tabindex="-1" role="dialog">
</div>

<script type="text/jscript">

    $(document).ready(function () {

        $("#CreateView").hide();

        var rowCount = $('#jobs li').length;
        if (rowCount > 1) {
            $('#DetailView').load('../InternalAssignment/Details');
            $('#DetailView').show();
        }

        $(".job").click(function (event) {
            var id = (this.id);
            $('#DetailView').load('../InternalAssignment/Details', { id: id });
            $('#DetailView').show();
        });

        $('#createNew').on('click', function () {
            $("#CreateView").show();
            $("#DetailView").addClass('fade')
            $("#CreateView").dialog({
                autoOpen: true,
                position: { within: window },
                width: 500,
                resizable: false,
                title: '',
                modal: true,
                open: function () {
                    $(this).load('@Url.Action("Create", "InternalAssignment")');
                },
                close: function () {
                    $("#CreateView").hide();
                    $("#DetailView").removeClass('fade')
                }
            });

        });

    });

    $(function () {
        $('body').on('click', '.modal-link', function (e) {
            e.preventDefault();
            $(this).attr('data-target', '#modal-container');
            $(this).attr('data-toggle', 'modal');
        });

        $('body').on('click', '.modal-close-btn', function () {
            $('#modal-container').modal('hide');
        });

        $('#modal-container').on('hidden.bs.modal', function () {
            $(this).removeData('bs.modal');
        });

        $('#CancelModal').on('click', function () {
            return false;
        });
    });

    $("#jobs li a").click(function () {
        $(this).parent().addClass('active').siblings().removeClass('active');

    });

</script>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")